apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: moon-pvc-126
  namespace: moon
spec:
  storageClassName: moon-retainer
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 3Gi

